# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ccb2b9e9f3ece34d5c13b99cf3bead3d4bffb4bed1fbea142397e640fcd7dc2ec2dd8f5f5f0a623005d5af7f81ab93a284f0d6d1c73912d274558997b035a8

test:
  secret_key_base: 0093ebda2dd6c44977e3f6206e8859ffa7a61ad96356338629d46a01efc4d809ef2e19d783ee54f07ec42219fd0728316801f71ce951d4fe7929857b89fd2db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
